name: ci

on:
  push:
  pull_request:

jobs:
  moonbit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonbitlang/setup-moonbit@v1
      - run: moon update
      - run: moon check --warn-list +73
      - run: moon test
      - run: moon info
