name: Test

on:
  push:
  pull_request:

jobs:
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Moon env (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libssl-dev
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> "$GITHUB_PATH"

      - name: Setup Moon env (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install gcc openssl
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> "$GITHUB_PATH"

      - name: Setup Moon env (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
          irm https://cli.moonbitlang.com/install/powershell.ps1 | iex
          echo "$HOME/.moon/bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Install Moon Wrapper
        run: |
          mkdir -p "$HOME/wrapper_bin"
          cp .github/workflows/moon-wrapper.sh "$HOME/wrapper_bin/moon"
          chmod +x "$HOME/wrapper_bin/moon"
          echo "$HOME/wrapper_bin" >> "$GITHUB_PATH"

      - name: Moon Code Checks & Formats
        run: |
          moon update
          moon check --deny-warn
          moon fmt --deny-warn
          git diff --exit-code
          moon info
          git diff --exit-code --ignore-blank-lines -- '*.mbti'
          moon build
          moon test --deny-warn
          moon run cmd/main
